### ISSUE TITLE
Put a link to github repo on site

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#5]
Took me forever to find this config. A link to https://github.com/davorg/planetperl or even to https://github.com/davorg/planetperl/issues/new would allow requesting additions to be easier.

**Comment by davorg** [comment]
Done

**Comment by matthewpersico** [comment]
+1

**Comment by matthewpersico** [comment]
Ok, I'm opening this again because today, I cannot find the link to https://github.com/davorg/planetperl on the page today. There are links to the Perlanet, the underlying code, but not to the content repo PlanetPerl. Am I just blind?

**Comment by davorg** [comment]
D'oh! You're right. Those links are wrong.

**Comment by matthewpersico** [comment]
I still can’t figure out how I didn’t notice that the other day. Sorry about that.

**Comment by davorg** [comment]
Really fixed now. https://github.com/davorg/planetperl/commit/dce4641c84198884a302c75b29c1450cbf9d3e0e

**Comment by matthewpersico** [comment]
Really checked now.
